### ISSUE TITLE
Coinbase app appearing as Browser 

### ISSUE THREAD

**Issue by RuthlessRuler** [1fexd/LinkSheet#126]
### Bug description

So, I am latest Nightly Build of App.

For some reasons, Coinbase App is always added to the list of supported Link Handling despite the app not detecting the app as browser under any settings.

I also tried with Browsers set to Whitelist with the following enabled:
1. brave
2. Firefox
3. Hermit

But it seems to pickup Coinbase. 
![Screenshot_20230627-203142_LinkSheet Nightly](https://github.com/1fexd/LinkSheet/assets/20885012/532e16a1-a187-4c68-983e-e8b827d3d940)

Also occurs on Stable app version too.

### Version

master-33d70cd-nightly 1687795896

### Device

Poco X3 Pro

### Android version

Android 13 (Stock)

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
Okay so I just checked and it turns out these guys declare their app as a browser, lol. 
Can you check if the app has some sort of "Wallet" or "Web3" functionality? That would explain why they declare their app as a browser (so a user can open a "Web3" site in the app and link their wallet). 

If it doesn't, I'm gonna introduce a blacklist that filters out apps known to **not** be browsers which declare themselves as such from LinkSheet's results.

**Comment by RuthlessRuler** [comment]
![Screenshot_20230628-010546_LinkSheet Nightly~2](https://github.com/1fexd/LinkSheet/assets/20885012/03c48b9b-f7b9-426f-92d7-252edfead370)
![Screenshot_20230628-010551_LinkSheet Nightly~2](https://github.com/1fexd/LinkSheet/assets/20885012/801abde9-c7f1-4cc7-91fc-b1d1206db434)
![Screenshot_20230628-010610_Permission controller~2](https://github.com/1fexd/LinkSheet/assets/20885012/2c539cc6-a4b2-4e20-8f3f-cee78ed512a2)

Though the app doesn't appear anywhere here, the app still shows up in results.
The app does have the Web3 Component that allows it to open Dapps and stuff as I checked.

Instead of direct blacklist, I suggest to list such apps on the App's Borwser Settings allowing user to tweak them.

**Comment by 1fexd** [comment]
Okay, so what's the usecase here? Do you always want to go to LinkSheets settings, set Coinbase to "show in results" (or something like that, not implemented yet), then click a link which you want to handle in Coinbase? Sounds tedious, and since they have actually browser functionality (DApp) I think it's not really a bug to display it.

**Comment by RuthlessRuler** [comment]
I don't use Web3 and more. 
I probably just want to hide this app forever for all URLS as I am not gonna use it for this.

So maybe showing it under browser settings and with option to hide it by using whitelist and more will be awesome.

**Comment by 1fexd** [comment]
What happens if you don't use LinkSheet? Does Coinbase then show up somehow?

**Comment by RuthlessRuler** [comment]
> What happens if you don't use LinkSheet? Does Coinbase then show up somehow?

If I don't use LinkSheet, it just open the links in the default browser. I don't see the app being shown anywhere.

**Comment by 1fexd** [comment]
Coinbase will now show up as a browser in LinkSheet, allowing you to exclude to not include it in your whitelist. Nightly is building right now, should be done in like 10 minutes, please check if it works for you, thanks!

**Comment by RuthlessRuler** [comment]
Works perfectly now.
Doesn't show up if not included in the whitelist.

Thanks a lot for the fix!
