### ISSUE TITLE
[Request] possible to connect LinkSheet in Personal and Work profile?

### ISSUE THREAD

**Issue by Nonanne** [1fexd/LinkSheet#139]
### Feature description

AFAIK, in android 13 support sync app data across personal and work profile (Connected work & personal apps Features)
I assumed this feature can help LinkSheet to access all/any profiles and open urls to app in other profiles.

Should be better if this excellent app can do this features!

**Comment by 1fexd** [comment]
> AFAIK, in android 13 support sync app data across personal and work profile (Connected work & personal apps Features)

Do you have more information on that one? Like some sort of documentation? Because I have experienced it the other way lately - there was an update recently and now work app screenshots go into the work profile's gallery (which is incredibly annoying).

Also, I assume you are using Shelter or Island/Insular to create a work profile? (personally I use the work profile option directly built into CalyxOS, even though I should have used Shelter as it provides more customizability)

> I assumed this feature can help LinkSheet to access all/any profiles and open urls to app in other profiles.

Hmmmm, _theoretically_, if you install LinkSheet in both profiles, this should be possible anyway, but I have to look into that.

> Should be better if this excellent app can do this features!

Thanks for the compliment :)

PS: please don't expect anything soon, I haven't had a lot of motivation recently and have completly missed my 1.0.0 milestone goal, so I am currently trying to get enough motivation to fix the remaining bugs and get another release out without all the missing 1.0.0 features I wanted to implement, as it has been a **while** since the last real release (doesn't bother me personally, since I just use nightly)

**Comment by Terrance** [comment]
I'd also be interested in some way of opening links across default/work profiles.

For context, I use Insular as a "work" profile to install copies of apps or prevent them from accessing main profile accounts.  I don't have a browser installed in the secondary profile, and ideally I want links to just open in the main profile's default browser.

The Android sharing framework supports cross-profile sharing: the share panel defaults to apps from the current profile, but has tabs letting you switch between default/work to select apps from the other profile.

Trying to open links in the work profile directly doesn't work as no browser is available there.

> if you install LinkSheet in both profiles, this should be possible anyway

I tried this, but LinkShare just gets stuck on "Loading link...", presumably as there's no browser for it to forward the request to.

<img src="https://github.com/1fexd/LinkSheet/assets/4025899/b4566818-657b-409e-8900-fbfc2c62f618" height="300">
<img src="https://github.com/1fexd/LinkSheet/assets/4025899/ce2518e3-88b8-4b9d-8abb-50bfed93eeeb" height="300">

(first screenshot is without LinkSheet installed in the work profile, second is after installing)

**Comment by 1fexd** [comment]
There's not really anything I can do here without special support by work profile providers as far as I can tell. But you can just install LinkSheet in both profiles, then enable "Share to" button in Settings -> Bottom Sheet, then select the second LinkSheet app throught the system share dialog.

**Comment by 1fexd** [comment]
Please check on the [latest nightly build](https://nightly.link/1fexd/LinkSheet/workflows/build-nightly/master/linksheet-nightly.zip), I just fixed an obscure bug the other day which may cause this.

**Comment by Terrance** [comment]
No change with `master-e919e6e-nightly` -- just to make sure we're on the same page, this is where I'm at (I have _Enable "Share to" button_ on in the Work profile, all other settings are default):

https://github.com/1fexd/LinkSheet/assets/4025899/058dab93-dc4e-471c-8ae5-d6e1371e4fbf

Note that there are no browsers installed in the Work profile (and the list in _Browser_ > _Preferred browser_ is empty).

Process-filtered logcat: [linksheet-logcat.log](https://github.com/1fexd/LinkSheet/files/12343373/linksheet-logcat.log)

Looks like there are a few potentially interesting lines in the log, including:

> E OplusBaseFile: isColorMetaEnable exception: java.lang.SecurityException: get application info: UID 1010536 requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS to access user 0.

**Comment by 1fexd** [comment]
I have fixed the issue - please test the latest nightly

**Comment by Terrance** [comment]
Looks like that works, thanks!  It's a bit of a clunky flow (tap link > Share to > Personal > choose browser), but that's mainly down to Android and this is certainly an improvement over links not working at all.  🙂

(NB. the layout sometimes doesn't fill the width and looks a bit funky:
<img src="https://github.com/1fexd/LinkSheet/assets/4025899/b7f78068-91f7-4ca8-8b6d-92c40bdb1d1d" width="300">
So far it's only happened on that no-browsers screen whilst in Android split-screen mode, though not consistently...)

**Comment by 1fexd** [comment]
Closing this for now, if any more questions/feature requests arise, please open a new issue.
