### ISSUE TITLE
Integrated Fediverse Redirect 

### ISSUE THREAD

**Issue by RuthlessRuler** [1fexd/LinkSheet#147]
### Feature description

It would be great if the Mastodon/Lemmy/Kbin and more redirect can be integrated as extension for the app.

There exists seprate apps called Mastodon Redirect & Lemmy Redirect. The hope is to integrate them within this to allow apps to open links from increasing number of instances.

The problem Fediverse Apps is that most of them don't handle links from other instances (eg. official Mastodon app will only appear for Mastodon.social & .online and etc).

**Comment by 1fexd** [comment]
Are these android apps? I can not seem to find them anywhere?

**Comment by RuthlessRuler** [comment]
> Are these android apps? I can not seem to find them anywhere?

https://github.com/zacharee/MastodonRedirect

**Comment by 1fexd** [comment]
Okay, so if I understand this correctly, if you currently open a link, LinkSheet opens, but since most Lemmy/Mastodon clients do not support all these domains MastodonRedirect [has hardcoded into its manifest](https://github.com/zacharee/MastodonRedirect/blob/main/mastodonredirect/src/main/AndroidManifest.xml#L41), they do not correctly show up in LinkSheet, right?

Is there any reason why opening MastodonRedirect from LinkSheet is not an option for you? Is it just inconvenient? My goal here is to duplicate only absolutely necessary functionality, and if there's already an app which has exactly this single purpose, why not let the user use it instead of basically copying its functionality into LinkSheet (and therefore creating yet another dependency which requires constant updates, which often are very tedious to implement)? 

Of course, I would still like to hear your take on that, so please enlighten me. Thanks :)

**Comment by RuthlessRuler** [comment]
So Mastodon Redirect is not really that amazing option, as each links needs to be enabled in settings. And it can lot of work for avg user.

If LinkSheet goes with JSON dependency in 1.0, then this could be useful where supported link is rewritten from og.com/@user/post to other.com/@user@og.com/post where other.com is a domain supported by the Fediverse app.

This will allow to use it with lot higher number of apps then the currently supported apps.

Additionally, it also uses additional number of taps to achieve the same, so if it could be simplified then it would be great.

**Comment by 1fexd** [comment]
> So Mastodon Redirect is not really that amazing option, as each links needs to be enabled in settings. And it can lot of work for avg user.
> 
> If LinkSheet goes with JSON dependency in 1.0, then this could be useful as the list can be independently updated making it more upto date. Also, supported link is rewritten from og.com/@user/post to other.com/@[user@og.com](mailto:user@og.com)/post where other.com is a domain supported by the Fediverse app.
> 
> This will allow to use it with lot higher number of apps then the currently supported apps.
> 
> Additionally, it also uses additional number of taps to achieve the same, so if it could be simplified then it would be great.

Okay, so you'd be okay with LinkSheet starting when you tap an Mastodon/Lemmy link which is in our JSON list of instances, and LinkSheet prefering known supported apps, right? Because currently, if you set up LinkSheet, but leave Mastodon Redirect as URL handler for these known Mastodon/Lemmy instances, links of these should automatically go through Mastodon Redirect instead of LinkSheet.

**Comment by RuthlessRuler** [comment]
Yes, as it stills allow you to open the links in browser incase you don't want to open in app.

**Comment by 1fexd** [comment]
Will evaluate later. Thanks for the suggestion.

**Comment by zacharee** [comment]
You can use LinkSheet to enable all the links at once in Mastodon/Lemmy Redirect or use Shizuku to do it.

**Comment by 1fexd** [comment]
> You can use LinkSheet to enable all the links at once in Mastodon/Lemmy Redirect or use Shizuku to do it.

I've tried the Shizuku method to enable all links for Mastodon Redirect, but it didn't work. Either there are too many links, or the developer has made a mistake. LinkSheet 1.0.0 will also support Shizuku to either disable or enable all app link handlers, which appears to work fine. Maybe I'm going to look into why Mastodon Redirect doesn't work.

**Comment by zacharee** [comment]
I've fixed it so 1.3.4 should work with Shizuku and LinkSheet now.

**Comment by zacharee** [comment]
I've fixed it so 1.3.4 should work with Shizuku and LinkSheet now.

**Comment by 1fexd** [comment]
Ohh you are the developer, didn't recognize you :laughing: 

Yeah, as already mentioned above, I'd rather somehow forward Mastodon/Lemmy stuff to your app instead of duplicationg/replicating your app's functionality into LinkSheet (because that would be more effort to maintain, and also kind of "steal" your work)

**Comment by 1fexd** [comment]
MastodonRedirect will have an option to set up link-handling via LinkSheet in the future. Please install MastodonRedirect to set up link-handling or use MastodonRedirect alltogether.

**Comment by nichu42** [comment]
@1fexd Pardon my ignorance, but how does this work? Mastodon Redirect does not show in the apps list of LinkSheet. /cc @zacharee

**Comment by 1fexd** [comment]
It's the other way around, Mastodon Redirect shows you an option to set it up in combination with LinkSheet. But that will only be available in either the LinkSheet nightly builds or the next release.

**Comment by nichu42** [comment]
@1fed
> It's the other way around, Mastodon Redirect shows you an option to set it up in combination with LinkSheet. But that will only be available in either the LinkSheet nightly builds or the next release.

Thanks for the clarification. I download the nightly, but Mastodon Redirect just shows an "Open LinkSheet" button. I can't find a way to auto-use LinkSheet from within Mastodon Redirect. But with the Nightly I can now see Mastodon Redirect in the app list and add all URLs manually. I don't know if this has to be done regularly (after each update of MR), though.

I have two more remarks, but I will open up separate issues for those.

**Comment by 1fexd** [comment]
@zacharee do you know what's going on here?

**Comment by zacharee** [comment]
Which version of Mastodon Redirect is it?

**Comment by nichu42** [comment]
Version 1.5.0

**Comment by zacharee** [comment]
Do you also have stable LinkSheet installed?

**Comment by nichu42** [comment]
> Do you also have stable LinkSheet installed?

Sorry, I can't tell. Since I was experimenting with Shizuku, the red bar in MR has disappeared. I was expecting that it will return if I uninstall all apps (MR + LS + Shizuku) and do a fresh install of MR, but that's not the case. 🤔

**Comment by zacharee** [comment]
Android persists domains enabled with Shizuku. Right now, the debug version of Fediverse Redirect has a button to revoke links through Shizuku, but I don't have builds released. I might put that button in the release version somewhere.
