### ISSUE TITLE
Opening Links in Firefox doesn't open in Native App

### ISSUE THREAD

**Issue by TheHawaiianKoala** [1fexd/LinkSheet#205]
### Bug description

Hello

I think I am misunderstanding how this app works. If I open any link (lets say youtube) from a search result in Firefox, It doesnt open in the native app. Rather it opens in Firefox. Although sharing works fine

### Version

0.0.33

### Device

Google Pixel 4

### Android version

Graphene OS 13

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
Yes, because when clicking a search result, the browser explicitly requests a non-browser app (which LinkSheet isn't) to handle the link (e.g. the Youtube app). If there is none installed, it opens in a new tab/the same tab instead (at least that's what Chrome/Chromium does). I built [LinkSheetCompat](https://github.com/1fexd/LinkSheetCompat) for this reason, just install it, then go to Settings -> Apps -> LinkSheetCompat and set it as linkhandler for `youtube.com`, it should then intercept clicks in browsers and forward them to LinkSheet.

**Comment by TheHawaiianKoala** [comment]
Does this mean that for every app, I would need LinkSheetCompat to have links for linkhandling? For example Aurora store and Reddit apps.

**Comment by 1fexd** [comment]
If you want LinkSheet to open when you click a link from, for example, Google search results, then yes.

**Comment by TheHawaiianKoala** [comment]
We can mark it as solved then imo
