### ISSUE TITLE
All supported links are not identified

### ISSUE THREAD

**Issue by Tanmandal** [1fexd/LinkSheet#31]
![Screenshot_2023-03-05-09-52-35-020_fe linksheet](https://user-images.githubusercontent.com/93572359/222941738-46f39bbd-8920-42f5-9a27-81c69751a9d0.jpg)
![Screenshot_2023-03-05-09-54-08-865_com tasomaniac openwith floss](https://user-images.githubusercontent.com/93572359/222941739-36a21e54-7e50-4c5e-83e0-00a20cf8df48.jpg)

 
Like the link
 t.meet 
Which is supported by google meet shows up in openwith but not in linksheet

**Comment by 1fexd** [comment]
What Android version are you using? Google Meet does not show up for me in OpenLinkWith for the domain `t.meet`. It also doesn't show up in LinkSheet, but that is the intended behavior, since Google Meet's manifest specifies that it only matches the short domains when the url path starts with a `/` (e.g. `t.meet/` or something like `t.meet/jsdkfljkasldfjlksdaklj` will match, but `t.meet` alone doesn't since, it doesn't contain a path):
![image](https://user-images.githubusercontent.com/58902674/222952911-46c96869-82a6-4b59-86ed-eb08edc1d9e0.png)

**Comment by Tanmandal** [comment]
Ok got it 
Got a similar behavior using flipkart.com link 
For example try this link
https://dl.flipkart.com/s/EriOnMNNNN

**Comment by 1fexd** [comment]
Flipkart Lite only supports links starting with **www.**

**Comment by Tanmandal** [comment]
But its working in openwith

**Comment by 1fexd** [comment]
Strange, it doesn't on my device

**Comment by Tanmandal** [comment]
Having same problem with twitter web app
I think what is the difference is that even when an app is set to open by default still openwith shows it in the list of apps but linksheet doesn't
Like if I share youtube link with linksheet it lists only the browsers but openwith lists all options

**Comment by 1fexd** [comment]
Twitter works fine for me.
