### ISSUE TITLE
Add a button to strip url parameters

### ISSUE THREAD

**Issue by dgudim** [1fexd/LinkSheet#91]
### Feature description

Currently you can either turn CleanUrl integration on or off globally. But in some rare cases I don't want to strip parameters from uls, a button or a switch would be really handy. Perhaps you could also add quick toggles for redirect/etc and hide them under a pop-up selector of some sorts

**Comment by 1fexd** [comment]
Have you encountered any links where this is necessary? Usually ClearURLs' rules work very well and don't break any websites.

**Comment by dgudim** [comment]
From the top of my head: email verification links and some aliexpress links

**Comment by 1fexd** [comment]
Could you please provide some of them (with redacted query parameters of course) so I can debug the issue as this should not happen. 

I am not sure if adding yet another (optional) button to the bottom sheet is a great user experience as it is already reaaally bloated, but I'll think about it.

**Comment by 1fexd** [comment]
> I can't remember the links. Buy I thought about it, they are pretty rare, maybe just add a small circle near the url if the parameters were stripped. And I dont think it's an issue on your side, because it behaves the same as "Clean share" android app and "CleanUrls" browser extension.

Strange, if this is an issue on the browser extension itself (the LinkSheet implementation uses the exact same rules) we should report that to them so it can be fixed in the extension as well.

> How about instead of the button, add settings (rule/exclusions) in the "Use CleanUrls" section, just like in "Enable LibRedirect".

Allowing the user to specify exclusions would mean that the user has to enter their own regex to match URLs which should be included, which is not very user friendly (and I don't think even power-users need such a feature); Also, having to specify rules yourself means that something is broken in ClearURLs as the user should never have to do that in order for some URLs to work (broken URLs should be reported on the ClearURLs issue tracker). I think our best bet is to just add the option to display an "Ignore" button, even though, as already mentioned, this is probably not an ideal solution as the bottom sheet is already very bloated. Besides that, when you turn on ClearURLs, why would you ever want to ignore it? (except for the case where ClearURL breaks URLs => report on their issue tracker)

**Comment by dgudim** [comment]
Hmm, makes sense, maybe we don't need a button after all. I'll report broken urls to their issue tracker then

**Comment by 1fexd** [comment]
Please report them to me first if you encounter an issue when using ClearURLs in LinkSheet so I can check first if it is an issue with my implementation before we raise an issue upstream.
